#  vi: set ft=ansible.yaml ts=2 sw=2 tw=0 :
---
- name: ensure package is installed
  apt: name=supervisor state=present
  sudo: yes
  when: supervisor_enabled

- name: ensure supervisor is started
  service: name=supervisor state=started
  sudo: yes
